### ISSUE TITLE
Broken cmake metadata?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/eigenpy-feedstock#116]
Just noticed this in https://github.com/conda-forge/pycppad-feedstock/pull/14:
```
CMake Error at $PREFIX/lib/cmake/eigenpy/eigenpyTargets.cmake:61 (set_target_properties):
  The link interface of target "eigenpy::eigenpy" contains:

    Python3::NumPy

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```
That's despite the fact that numpy is clearly there; eigenpy should search for numpy and then use that to link. Ideally, this feedstock should add a test for that (here's a simple [example](https://github.com/conda-forge/thrift-cpp-feedstock/blob/main/recipe/cmake_test/CMakeLists.txt) how to do that).

**Comment by jcarpent** [comment]
Solved via new release of PyCppAD
