### ISSUE TITLE
Pinocchio not compiling anymore

### ISSUE THREAD

**Issue by jcarpent** [conda-forge/eigenpy-feedstock#9]
Issue: PR #8 has changed the location of the INSTALL_PREFIX variable on UNIX systems. As mentioned in https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html, the variable `LIBRARY_PREFIX`is only defined on Windows. 
@seanyen @wolfv Could you provide some guidance to restore the previous behavior on LINUX and UNIX systems?

**Comment by jcarpent** [comment]
This a wrong interpretation from my side. Sorry for the burden.

**Comment by wolfv** [comment]
I just double checked and it seems to only do something on Windows (even though we probably should have done 

```
patches:
   - win.patch  # [win]
```

Did you figure the linker issue out?
